"""Multi-walker metadynamics — orchestration layer.

PLUMED's METAD/OPES_METAD bias actions support a multi-walker mode via
the inline keywords ``WALKERS_N``, ``WALKERS_ID``, ``WALKERS_DIR`` and
``WALKERS_RSTRIDE``. Each walker runs as an independent process, writes
its own ``HILLS.<walker_id>`` file in a shared directory, and reads
everyone else's HILLS files at every ``WALKERS_RSTRIDE`` step so the
deposited bias is collective. This module provides the orchestration
around that PLUMED feature (PLUMED also has a separate top-level
``MULTIPLE_WALKERS`` action; we use the inline form because that's what
``quantum_engine.mlff.plumed_runner`` already emits):

* :class:`WalkerSweepConfig` — single typed dataclass with every
  parameter for the sweep (no YAML hierarchy gymnastics).
* :func:`run_walker` — entry point a SLURM array task calls. Sets up the
  walker's working directory, decides whether to resume, runs MD with a
  multi-walker-configured PLUMED, and writes round-tagged outputs.
* :func:`merge_walkers` — post-sweep aggregation: read every walker's
  HILLS into a single :class:`quantum_engine.analysis.fes.HillsData` (delegates to
  :func:`quantum_engine.analysis.fes.parse_hills_dir`).

The matching SLURM array job submitter lives in
:mod:`quantum_engine.slurm.submit_walkers` so the orchestration stays cleanly
separated from the cluster-specific submission policy.

This is a modernised re-implementation of enz-ts's
``slurm/sbatch_simulation.py`` + ``run_simulation.py`` + ``submit_rounds.sh``
+ ``launch_walkers.sh`` chain. Differences:

* No global ``os.chdir`` — every path is explicit.
* No shell scripts. The sbatch script is generated by Python; rounds are
  chained via ``--dependency=afterany`` job ids returned by sbatch.
* Resume detection uses the per-walker output dir's contents only —
  no W&B / config-file roundtripping.
* Failure mode if a walker crashes mid-round: the round's leftover
  partial HILLS remains, and the next round's walker reads it from
  ``<out>/WALKER_<id>/HILLS.<id>`` like normal — no special restart
  bookkeeping required.

Caveat: PLUMED multi-walker requires a shared filesystem with sub-second
visibility for the HILLS files. NFS is fine; Lustre is fine; tmpfs-only
nodes are not. Pass ``shared_dir`` to point at a known-good shared FS.
"""
from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger("quantum_engine.ops.mtd_walkers")


# ─────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────

@dataclass
class WalkerSweepConfig:
    """All parameters for a multi-walker MTD sweep.

    Only fields with no default need to be specified at the call site;
    everything else has a sensible default for a typical enzymatic
    metadynamics run.
    """

    # Required
    structure: Path                 # input structure (PDB or CIF)
    output_dir: Path                # parent dir for the sweep
    cv: Any                         # quantum_engine.mlff.plumed_runner CV instance
                                    # (DistanceCV, DistanceDifferenceCV, AngleCV, ...)

    # Walker / round counts
    n_walkers: int = 8
    n_rounds: int = 4
    walltime_per_round: str = "12:00:00"
    # Stagger walker startup by N seconds × walker_id to avoid the FS
    # metadata storm of N walkers all touching shared_hills/ at once.
    # 0 disables. ~5 s is plenty on NFS.
    startup_stagger_s: int = 5

    # MD params
    timestep_fs: float = 0.5
    temperature_K: float = 300.0
    total_time_ps_per_round: float = 50.0
    friction_per_ps: float = 1.0

    # MTD params
    method: str = "metad"  # 'metad' or 'opes'
    pace_steps: int = 500
    sigma: list[float] | None = None  # per-CV bandwidths (Å typically)
    bias_height_kJ_mol: float = 1.0
    bias_factor: float = 10.0          # well-tempered γ
    barrier_kJ_mol: float | None = None  # OPES only

    # MLFF
    calculator_model: str = "mace-mp"
    device: str = "cpu"
    dtype: str = "float32"
    charge: int | None = None
    constraint_atoms: list[int] | None = None  # FixAtoms indices

    # Equilibration: optional 1-shot equilibration MD before round 1
    equilibrate_first_round: bool = False
    equilibration_time_ps: float = 5.0

    # SLURM
    partition: str = "cpu"
    cpus_per_walker: int = 4
    mem_per_walker: str = "16G"
    gres: str | None = None  # e.g. 'gpu:1' for GPU walkers

    # Misc
    job_name_prefix: str = "qcb_mtd"

    # Internal: filled by submit_walker_sweep at runtime
    sweep_id: str | None = None  # auto-assigned trial id

    def __post_init__(self) -> None:
        self.structure = Path(self.structure)
        self.output_dir = Path(self.output_dir)
        if not self.structure.is_file():
            raise FileNotFoundError(f"structure not found: {self.structure}")
        if self.method not in ("metad", "opes"):
            raise ValueError(f"method must be 'metad' or 'opes', got {self.method!r}")
        if self.n_walkers < 1:
            raise ValueError("n_walkers must be ≥ 1")
        if self.n_rounds < 1:
            raise ValueError("n_rounds must be ≥ 1")

    def walker_dir(self, walker_id: int) -> Path:
        """Per-walker working directory under the sweep output_dir."""
        return self.output_dir / f"WALKER_{walker_id:03d}"

    def shared_hills_dir(self) -> Path:
        """Directory PLUMED reads/writes shared HILLS to."""
        return self.output_dir / "shared_hills"


# ─────────────────────────────────────────────────────────────────────
# Walker entry point (called by SLURM array task)
# ─────────────────────────────────────────────────────────────────────

def run_walker(
    config: WalkerSweepConfig,
    walker_id: int,
    round_num: int,
    *,
    equilibrate: bool = False,
) -> dict:
    """Run a single walker for one round.

    Decides on entry whether prior rounds completed in
    ``config.walker_dir(walker_id)`` (each round writes a
    ``walker_summary.json`` on success). On resume the per-walker state
    is just whatever lives on disk — PLUMED reads the shared HILLS
    history; we don't restart velocities. The new round writes its own
    output to ``round_NNN/`` regardless.

    The MD itself is delegated to :func:`quantum_engine.mlff.metadynamics` for the
    actual integrator, and :mod:`quantum_engine.mlff.plumed_runner` for the multi-
    walker PLUMED setup. We just hand them the right paths.

    Args:
        config: the sweep config.
        walker_id: 0-indexed walker id (typically ``$SLURM_ARRAY_TASK_ID``).
        round_num: 1-indexed round counter.
        equilibrate: if True, run an unbiased equilibration MD before
            metadynamics. Only meaningful for round 1.

    Returns:
        dict with keys {status, walker_id, round_num, n_steps, hills_file}.
    """
    if walker_id < 0 or walker_id >= config.n_walkers:
        raise ValueError(
            f"walker_id {walker_id} out of range [0,{config.n_walkers})"
        )

    walker_root = config.walker_dir(walker_id)
    walker_root.mkdir(parents=True, exist_ok=True)
    config.shared_hills_dir().mkdir(parents=True, exist_ok=True)

    # Stagger walker startups so N walkers don't simultaneously touch the
    # shared HILLS dir (NFS metadata storm).
    if config.startup_stagger_s > 0 and walker_id > 0:
        import time
        delay = walker_id * config.startup_stagger_s
        log.info(f"[walker {walker_id}] startup stagger: sleep {delay}s")
        time.sleep(delay)

    # Resume detection — done BEFORE we mkdir the current round, so we don't
    # see ourselves in the prior-rounds list. We also require an actual
    # round artefact (a written walker_summary.json) to count as "ran" —
    # an empty round dir from a prior crashed attempt should re-run, not
    # be treated as a successful prior round.
    completed_rounds = [
        d for d in walker_root.glob("round_*")
        if d.is_dir() and (d / "walker_summary.json").is_file()
    ]
    is_resume = len(completed_rounds) > 0
    round_dir = walker_root / f"round_{round_num:03d}"
    round_dir.mkdir(exist_ok=True)
    log.info(
        f"[walker {walker_id}] round {round_num}: "
        f"{'RESUME (' + str(len(completed_rounds)) + ' prior rounds)' if is_resume else 'FRESH'}; "
        f"out → {round_dir}"
    )

    # Build the PLUMED multi-walker spec. PlumedRunSpec wants cvs (list)
    # and method.cv_name; sigma is a *scalar* (PLUMED handles per-CV
    # bandwidths via the SIGMA= keyword on the method line, and qcb's
    # current method dataclasses are 1-CV).
    from quantum_engine.mlff.plumed_runner import (
        PlumedRunSpec, WTMetadynamics, OPESMetadynamics, run_plumed_md,
    )
    sigma_val = (config.sigma[0] if isinstance(config.sigma, (list, tuple))
                 and config.sigma else 0.05)
    if config.method == "metad":
        method = WTMetadynamics(
            cv_name=config.cv.name,
            sigma=sigma_val,
            height_kJ=config.bias_height_kJ_mol,
            bias_factor=config.bias_factor,
            pace_steps=config.pace_steps,
            file="HILLS",
        )
    else:
        method = OPESMetadynamics(
            cv_name=config.cv.name,
            sigma=sigma_val,
            barrier_kJ=config.barrier_kJ_mol or 50.0,
            pace_steps=config.pace_steps,
        )
    spec = PlumedRunSpec(
        cvs=[config.cv],
        method=method,
        walker_id=walker_id,
        n_walkers=config.n_walkers,
        walker_dir=str(config.shared_hills_dir().resolve()),
    )

    # Materialise the calculator + atoms + run MD
    from quantum_engine.calc import make_calc
    import ase.io

    atoms = ase.io.read(str(config.structure))
    if config.charge is not None:
        atoms.info["charge"] = config.charge
    calculator = make_calc(
        config.calculator_model,
        device=config.device,
        default_dtype=config.dtype,
        charge=config.charge,
    )
    atoms.calc = calculator

    constraint = None
    if config.constraint_atoms:
        from ase.constraints import FixAtoms
        constraint = FixAtoms(indices=list(config.constraint_atoms))

    # Optional equilibration before the very first round. We re-read the
    # equilibrated geometry from disk so the production MD sees the
    # relaxed positions (keeping the original `atoms` object would risk
    # silently dropping changes if `run_md` returned a copy or used a
    # restart trajectory).
    if equilibrate and round_num == 1 and not is_resume:
        from quantum_engine.ops.md import run as run_md
        log.info(f"[walker {walker_id}] equilibrating {config.equilibration_time_ps} ps")
        equil_dir = round_dir / "equil"
        run_md(
            atoms=atoms,
            outdir=str(equil_dir),
            timestep_fs=config.timestep_fs,
            temperature_K=config.temperature_K,
            total_time_ps=config.equilibration_time_ps,
            friction_per_ps=config.friction_per_ps,
        )
        equil_final = equil_dir / "final.xyz"
        if equil_final.is_file():
            atoms = ase.io.read(str(equil_final))
            atoms.calc = calculator

    # Production MTD with PLUMED multi-walker. Seed packs walker_id and
    # round_num into a non-colliding 32-bit int (1M slot per walker; up
    # to 1M rounds before wraparound).
    seed = (walker_id * 1_000_000 + round_num) & 0xFFFFFFFF
    result = run_plumed_md(
        atoms=atoms,
        calculator=calculator,
        spec=spec,
        outdir=round_dir,
        timestep_fs=config.timestep_fs,
        total_time_ps=config.total_time_ps_per_round,
        temperature_K=config.temperature_K,
        friction_per_ps=config.friction_per_ps,
        constraint=constraint,
        seed=seed,
    )
    # n_steps is reported by run_plumed_md if available; otherwise
    # compute the planned count for the summary file.
    n_steps = result.get("n_steps") if isinstance(result, dict) else None
    if n_steps is None:
        n_steps = int(config.total_time_ps_per_round * 1000 / config.timestep_fs)

    # Walker-local summary for downstream merge
    summary = {
        "status": "completed",
        "walker_id": walker_id,
        "round_num": round_num,
        "n_steps": n_steps,
        "round_dir": str(round_dir),
        "hills_file": str(config.shared_hills_dir() / f"HILLS.{walker_id}"),
    }
    (round_dir / "walker_summary.json").write_text(json.dumps(summary, indent=2))
    return summary


# ─────────────────────────────────────────────────────────────────────
# Post-sweep merge
# ─────────────────────────────────────────────────────────────────────

def merge_walkers(output_dir: Path) -> dict:
    """Aggregate every walker's HILLS for a finished sweep.

    Looks first under ``output_dir/shared_hills/`` for the multi-walker
    layout PLUMED writes (``HILLS.<id>``), and falls back to the older
    ``WALKER_<id>/HILLS`` per-walker layout that some enz-ts runs used.
    PLUMED restart-backup files (``bck.*HILLS*``) are filtered out.

    Returns a dict ``{n_walkers, n_hills_total, hills: HillsData}`` ready
    to feed into :func:`quantum_engine.analysis.fes.fes_from_hills_2d` etc.
    """
    import re
    output_dir = Path(output_dir)
    shared = output_dir / "shared_hills"
    paths: list[Path] = []
    if shared.is_dir():
        paths = sorted(p for p in shared.iterdir()
                       if re.fullmatch(r"HILLS\.\d+", p.name))
    if not paths:
        paths = sorted(output_dir.glob("WALKER_*/HILLS"))
    if not paths:
        raise FileNotFoundError(
            f"no HILLS files found under {output_dir}. Did the sweep finish?"
        )
    log.info(f"merging {len(paths)} walker HILLS files")
    return _merge_hills_paths(paths)


def _merge_hills_paths(paths) -> dict:
    """Merge an explicit list of HILLS paths into one :class:`HillsData`.

    The walker id is parsed from each path's *basename* (or its parent
    dir's basename for the per-walker layout) — never from the full
    string, to avoid an outer ``WALKER_007`` directory tagging every
    file as walker 7.
    """
    import re
    import numpy as np
    from quantum_engine.analysis.fes import parse_hills, HillsData

    parts: list[HillsData] = []
    walker_ids: list[np.ndarray] = []
    cv_names: list[str] | None = None
    bias_factor = 1.0
    for p in paths:
        h = parse_hills(p)
        if cv_names is None:
            cv_names = h.cv_names
            bias_factor = h.bias_factor
        elif h.cv_names != cv_names:
            raise ValueError(
                f"CV-name mismatch between walkers: "
                f"{cv_names} vs {h.cv_names} ({p})"
            )
        # Walker id from filename "HILLS.<id>" or parent dir "WALKER_<id>"
        m = re.fullmatch(r"HILLS\.(\d+)", p.name)
        wid = int(m.group(1)) if m else None
        if wid is None:
            m = re.match(r"WALKER_(\d+)", p.parent.name)
            wid = int(m.group(1)) if m else -1
        parts.append(h)
        walker_ids.append(np.full(len(h.time_ps), wid, dtype=int))

    return {
        "n_walkers": len(parts),
        "n_hills_total": sum(len(h.time_ps) for h in parts),
        "hills": HillsData(
            time_ps=np.concatenate([h.time_ps for h in parts]),
            cv=np.concatenate([h.cv for h in parts]),
            sigma=np.concatenate([h.sigma for h in parts]),
            height_kJ=np.concatenate([h.height_kJ for h in parts]),
            bias_factor=bias_factor,
            cv_names=cv_names or [],
            walker_id=np.concatenate(walker_ids),
        ),
    }
